### ISSUE TITLE
'pretty: true' not working

### ISSUE THREAD

**Issue by scottmartin** [chrisyip/koa-jade#13]
I have the following jade object:

```javascript
var Jade = require('koa-jade');

var jade = new Jade({
  viewPath: Path.join(__dirname, '..', 'app', 'templates'),
  pretty: true,
  basedir: Path.join(__dirname, '..', 'app', 'templates')
});

app.use(jade.middleware);
```

My templates are showing up correctly but they are not using Jade's pretty print option.

```html
<!DOCTYPE html><html><head><title>Testing</title></head><body><h1>This is a test</h1><p>Hello World!</p></body></html>
```

**Comment by chrisyip** [comment]
Fixed, thanks.

**Comment by scottmartin** [comment]
No problem. Thank you for contributing the middleware. I just started playing with Koa now that Node.js supports generators by default. I really like it so far.

**Comment by chrisyip** [comment]
Yes, Koa is a great framework :-)
