### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by danieldahan** [chrisyip/koa-jade#14]
Hi, 

I keep getting this error when I call this.render using koa-jade:

-----------------------------------------------------------

server error [RangeError: Maximum call stack size exceeded] { request:
   { method: 'GET',
     url: '/daniel',
     header:
      { 'x-real-ip': '10.211.55.2',
        'x-forwarded-for': '10.211.55.2',
        host: 'docs.sandbox.local:80',
        'x-nginx-proxy': 'true',
        connection: 'close',
        'cache-control': 'max-age=0',
        accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
        'upgrade-insecure-requests': '1',
        'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.80 Safari/537.36',
        'accept-encoding': 'gzip, deflate, sdch',
        'accept-language': 'en-US,en;q=0.8',
        cookie: '_ga=GA1.2.1728672733.1439768627' } },
  response:
   { status: 200,
     message: 'OK',
     header:
      { 'access-control-allow-origin': '*',
        'access-control-allow-methods': 'GET,HEAD,PUT,POST,DELETE',
        'cache-control': 'no-cache',
        'content-type': 'text/html; charset=utf-8',
        'content-length': '19' } },
  app: { subdomainOffset: 2, env: 'development' },
  originalUrl: '/daniel',
  req: '<original node req>',
  res: '<original node res>',
  socket: '<original node socket>' }

-----------------------------------------------------------

This is the code:

'use strict';
'use esnext';

function *base(route, next) {
	yield this.render('base', {
		title: 'Docs',
		styles: [
            // materialize
			'/materialize.min.css',

            // material icons
			'/css/materialdesignicons.min.css',

			// graphkit
			'/app.css'
		],
		vendors: [
			// jquery
			'/jquery.min.js',

			// angular
			'/angular.min.js',
			'/angular-aria.min.js',
			'/angular-route.min.js',

			// materialize
			'/materialize.min.js',

			// d3
			'/d3.min.js'
		],
		packages: [
			// app
			'/app.js',
			'/auth.js',
			'/connect.js',
			'/http.js',
			'/router.js'
		]
	}, true);

    if (undefined !== next) {
		yield next;
    }
}

function *index(route, next) {
	yield this.render('routes/index', {}, true);
}

function *profile(route, next) {
	yield this.render('routes/profile', {}, true);
}

function *error(route, next) {
    yield this.render('routes/error404', {}, true);
}

module.exports = function(app) {
	const koaRoute = require('koa-route');
	const koaJade = require('koa-jade');
	const jade = new koaJade({
		viewPath: __dirname + '/src/views',
		debug: 'development' == app.env,
		pretty: 'development' == app.env,
		compileDebug: 'development' == app.env,
		locals: {
			title: 'Docs'
		},
		basedir: '/',
		noCache: true,
		helperPath: [
			//'path/to/jade/helpers',
			//{ random: 'path/to/lib.js' },
		]
	});

	app.use(jade.middleware);

	// base
	app.use(koaRoute.get('/', base));
	app.use(koaRoute.get('/a/welcome', base));
	app.use(koaRoute.get('/:username', base));

	// index
	app.use(koaRoute.get('/route/index', index));

	// profile
	app.use(koaRoute.get('/route/profile', profile));
};

**Comment by qw3r** [comment]
@danieldahan Can you, please explain how did you managed to solve this issue?

**Comment by albertogasparin** [comment]
I've solved it by removing `yeld`:
```js
router.get('/', function *() {
  this.render('index', { a: b });
});
```
However it might not be the behaviour you want.

**Comment by iDev0urer** [comment]
Can we reopen this until there is a fix that doesn't require removing yield statements? They're kind of important

**Comment by danieldahan** [comment]
I looked over my code, and I also removed the yield call.

**Comment by chrisyip** [comment]
`this.render` doesn't require `yield` statement, it just a **normal function**.

Here's the reasons:

1. Normal function is faster then generator function:

```
iojs 1.6.4
Normal function x 163,231 ops/sec ±1.33% (180 runs sampled)
Generator function x 74,904 ops/sec ±1.86% (173 runs sampled)
```

2. Koa team encourages to use normal functions (see `v2`):

```js
app.use(ctx => {
  ctx.body = 'Hello World';
})
```

I'll update the doc.

**Comment by ladytellur** [comment]
@chrisyip some of us just wants to use koa@1 until async/await will become native in stable Node version

**Comment by chrisyip** [comment]
@ladytellur `koa-pug` supports `koa@1` and `koa@2`, just use `this.render()` without `yield`:

```js
const app = new Koa
const pug = new Pug({ /* options */ })
pug.use(app)

app.use(function* () {
  this.render('index')
})
```
