### ISSUE TITLE
If the view provided is a folder, pick index.jade as default

### ISSUE THREAD

**Issue by SamVerschueren** [chrisyip/koa-jade#9]
Hi

If the view folder structure looks like this

```
- views
 |--- home
    |--- index.jade
```

In express you can do the following

```
res.render('home');
```

But with ```koa-jade```, it looks for ```home.jade```. Maybe, if the path provided is a directory, try to find ```index.jade``` first, and then throw an error if that one does not exist.

If I find the time, I will create a pull request for this

**Comment by chrisyip** [comment]
I'm not familiar with express, do you know how express handles the following folder structure?

```
- views
  |--- home
    |--- index.jade
  |--- home.jade
```

**Comment by SamVerschueren** [comment]
I just tested it and then he first looks if the file ```home.jade``` exists, if it does it will render that one, otherwise in this case it will render ```home/index.jade```.

**Comment by chrisyip** [comment]
Thanks, express does what I expected :-)

**Comment by SamVerschueren** [comment]
Will you accept a PR if I made one?

**Comment by chrisyip** [comment]
Sure. But I'm working on it now.

**Comment by SamVerschueren** [comment]
Alright, thanks!
